2025-06-06 19:51:49,234 - ERROR - Reconnect failed
Traceback (most recent call last):
  File "c:\Users\juanb\OneDrive\Documents\GitHub\SLowMO-SDC-juan\SLowMO-SDC\client-server2\client\client3.py", line 1500, in reconnect_socket
    sio.connect(SERVER_URL, wait_timeout=5)
    ~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\juanb\AppData\Local\Programs\Python\Python313\Lib\site-packages\socketio\client.py", line 159, in connect
    raise exceptions.ConnectionError(exc.args[0]) from None
socketio.exceptions.ConnectionError: HTTPConnectionPool(host='192.168.1.146', port=5000): Max retries exceeded with url: /socket.io/?transport=polling&EIO=4&t=1749235904.2255862 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000001F334905BA0>, 'Connection to 192.168.1.146 timed out. (connect timeout=5)'))
2025-06-06 21:15:37,987 - ERROR - packet queue is empty, aborting
2025-06-07 20:42:14,149 - ERROR - Reconnect failed
Traceback (most recent call last):
  File "c:\Users\juanb\OneDrive\Documents\GitHub\SLowMO-SDC-juan\SLowMO-SDC\client-server2\client\client3.py", line 1577, in reconnect_socket
    sio.connect(SERVER_URL, wait_timeout=5)
    ~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\juanb\AppData\Local\Programs\Python\Python313\Lib\site-packages\socketio\client.py", line 159, in connect
    raise exceptions.ConnectionError(exc.args[0]) from None
socketio.exceptions.ConnectionError: HTTPConnectionPool(host='192.168.1.146', port=5000): Max retries exceeded with url: /socket.io/?transport=polling&EIO=4&t=1749325331.9136374 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000201DC705090>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
2025-06-07 20:42:27,025 - ERROR - Reconnect failed
Traceback (most recent call last):
  File "c:\Users\juanb\OneDrive\Documents\GitHub\SLowMO-SDC-juan\SLowMO-SDC\client-server2\client\client3.py", line 1577, in reconnect_socket
    sio.connect(SERVER_URL, wait_timeout=5)
    ~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\juanb\AppData\Local\Programs\Python\Python313\Lib\site-packages\socketio\client.py", line 159, in connect
    raise exceptions.ConnectionError(exc.args[0]) from None
socketio.exceptions.ConnectionError: HTTPConnectionPool(host='192.168.1.146', port=5000): Max retries exceeded with url: /socket.io/?transport=polling&EIO=4&t=1749325344.9123776 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000201DC705E50>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
2025-06-07 20:42:38,675 - ERROR - Reconnect failed
Traceback (most recent call last):
  File "c:\Users\juanb\OneDrive\Documents\GitHub\SLowMO-SDC-juan\SLowMO-SDC\client-server2\client\client3.py", line 1577, in reconnect_socket
    sio.connect(SERVER_URL, wait_timeout=5)
    ~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\juanb\AppData\Local\Programs\Python\Python313\Lib\site-packages\socketio\client.py", line 159, in connect
    raise exceptions.ConnectionError(exc.args[0]) from None
socketio.exceptions.ConnectionError: HTTPConnectionPool(host='192.168.1.146', port=5000): Max retries exceeded with url: /socket.io/?transport=polling&EIO=4&t=1749325356.5966818 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000201DC718C30>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
2025-06-07 22:14:18,417 - INFO - Attempting to reconnect to http://192.168.1.146:5000...
2025-06-07 22:14:19,069 - INFO - Restarting stream after reconnect...
2025-06-07 22:14:22,338 - INFO - Attempting to reconnect to http://192.168.1.146:5000...
2025-06-07 22:14:22,966 - INFO - Restarting stream after reconnect...
2025-06-07 22:27:32,144 - INFO - LIDAR metrics recording started.
2025-06-07 22:27:35,945 - INFO - LIDAR metrics recording saved to c:\Users\juanb\OneDrive\Documents\GitHub\SLowMO-SDC-juan\SLowMO-SDC\client-server2\client\recordings\lidar_2025-06-07_22-27-35.csv
2025-06-07 22:32:36,468 - INFO - LIDAR metrics recording started (live data only, relative timestamps).
2025-06-07 22:32:41,341 - INFO - LIDAR metrics recording saved to c:\Users\juanb\OneDrive\Documents\GitHub\SLowMO-SDC-juan\SLowMO-SDC\client-server2\client\recordings\lidar_2025-06-07_22-32-41.csv
2025-06-07 22:35:01,139 - INFO - Attempting to reconnect to http://192.168.1.146:5000...
2025-06-07 22:35:06,439 - INFO - LIDAR metrics recording started (live data only, relative timestamps).
2025-06-07 22:35:10,002 - INFO - LIDAR metrics recording saved to c:\Users\juanb\OneDrive\Documents\GitHub\SLowMO-SDC-juan\SLowMO-SDC\client-server2\client\recordings\lidar_2025-06-07_22-35-09.csv
